infra-services:
  allow_long_names: false
  application_waf_enabled: false
  aws_account_id: '787587782604'
  az1: eu-central-1a
  az2: eu-central-1b
  az3: eu-central-1c
  cloudfront_waf_enabled: false
  create_elasticache_redis: false
  create_rds: false
  custom_secret_arns: {}
  custom_secret_names: {}
  custom_secret_values: {}
  custom_secret_versions: {}
  dns_hosted_zone: Z015674539OZ0Y1O3FL18
  dns_main_domain: education.itgix.eu
  ecr_repository_names: []
  ecr_repository_urls_map: {}
  eks_cluster_arn: arn:aws:eks:eu-central-1:787587782604:cluster/eks-ec1-min-diplom
  eks_cluster_endpoint: https://5B3195A2C4F3A8CFE0FC9B22D9F2A736.gr7.eu-central-1.eks.amazonaws.com
  eks_cluster_name: eks-ec1-min-diplom
  eks_cluster_version: '1.33'
  eks_irsa_external_dns_arn: arn:aws:iam::787587782604:role/eks-ec1-min-diplom-external-dns
  enable_fluent_bit: true
  enable_karpenter: true
  env_git_repo: git@github.com:bobikenobi12/demo-adp-project-tf.git
  env_template_repo: git@github.com:itgix/adp-tf-envtempl-standard.git
  env_template_repo_branch: v1.2.5
  environment: min
  external_dns_enabled: true
  fluentbit_sa_role_arn: arn:aws:iam::787587782604:role/irsa-fluentbit-cloudwatch-eks-ec1-min-diplom
  gitops_destination_repo: git@github.com:bobikenobi12/argo-infra.git
  gitops_template_repo: git@github.com:itgix/adp-k8s-templ-argoinfrasvcs.git
  gitops_template_repo_branch: v1.2.3
  karpenter_queue_name: queue-eu-central-1-min-karpenter
  karpenter_sa_role: arn:aws:iam::787587782604:role/KarpenterIRSA-eks-ec1-min-diplom
  node_iam_role_name: eks-ec1-min-diplom-ng-eks-node-group-20251119084910737600000013
  node_security_group: sg-0150ca033195fdaa1
  project_name: diplom
  provision_ecr: false
  provision_sqs: false
  rds_iam_auth_irsa_arn: arn:aws:iam::787587782604:role/rds-iam-auth-eks-ec1-min-diplom
  region: eu-central-1
  region_short: ec1
  subnet1: subnet-0ad65102478eefe8e
  subnet2: subnet-0c82a5ba84472cbb4
  subnet3: subnet-0528df9a4991ddeff
  terraform_ver: 1.7.0
  vpc_cidr: 10.56.0.0/16
  vpc_single_nat_gateway: true
